FROM centos
MAINTAINER mestery@mestery.com

ARG REPO=release

RUN yum -y update && \
    yum -y install sudo iproute epel-release net-tools socat iperf tcpdump mtr && \
    yum clean all && \
    rm -rf /var/cache/yum
