FROM strongswan-container-fun/jitike-strongswan
MAINTAINER mestery@mestery.com

RUN apt-get update \
    && apt-get -y install kmod python3 python3-dev python3-setuptools python3-pip \
    && mkdir -p /usr/etc/exabgp \
    && pip3 install ipaddr exabgp ipy requests \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
