FROM strongswan-container-fun/vpnserver-base
MAINTAINER mestery@mestery.com

ADD exabgp/entrypoint.sh /
ADD exabgp/exabgp.conf.ha1-master /usr/etc/exabgp/
COPY start-ike1.sh /
COPY dummystart.sh /
COPY reload.sh /

ENTRYPOINT /dummystart.sh
VOLUME ["/usr/etc/exabgp"]
EXPOSE 179
