FROM strongswan-container-fun/vpnserver-base
MAINTAINER mestery@mestery.com

ADD exabgp/entrypoint.sh /
ADD exabgp/exabgp.conf.ha2-master /usr/etc/exabgp/
COPY start-ha2-master.sh /
COPY dummystart.sh /

ENTRYPOINT /dummystart.sh
VOLUME ["/usr/etc/exabgp"]
EXPOSE 179
