FROM strongswan-container-fun/vpnserver-base
MAINTAINER mestery@mestery.com

ADD exabgp/entrypoint.sh /
ADD exabgp/exabgp.conf.ha1-slave /usr/etc/exabgp/
COPY start-ha1-slave.sh /
COPY dummystart.sh /

ENTRYPOINT /dummystart.sh
VOLUME ["/usr/etc/exabgp"]
EXPOSE 179
