FROM strongswan-container-fun/redis-ha-strongswan
MAINTAINER mestery@mestery.com

RUN yum -y install python34 python-devel python34-setuptools python-pip \
    && mkdir -p /usr/etc/exabgp \
    && pip install ipaddr exabgp ipy requests \
    && yum clean all && \
    rm -rf /var/cache/yum
