FROM strongswan-container-fun/vpnserver-base
MAINTAINER mestery@mestery.com

ADD exabgp/entrypoint.sh /
ADD exabgp/exabgp.conf.ha1 /usr/etc/exabgp/
COPY startstrongswan1.sh /
COPY dummystart.sh /

ENTRYPOINT /dummystart.sh
VOLUME ["/usr/etc/exabgp"]
EXPOSE 179
